"""initial schema

Revision ID: 10eaeff03c27
Revises: 
Create Date: 2026-09-16 13:30:36.847203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10eaeff03c27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent', 'key', name='uq_agent_memory_agent_key')
    )
    op.create_index(op.f('ix_agent_memory_agent'), 'agent_memory', ['agent'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_table('body_composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_kg', sa.Float(), nullable=True),
    sa.Column('bone_kg', sa.Float(), nullable=True),
    sa.Column('water_pct', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'measured_at', name='uq_body_comp_source_measured_at')
    )
    op.create_index(op.f('ix_body_composition_measured_at'), 'body_composition', ['measured_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_chat_id'), 'conversations', ['chat_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories_active', sa.Float(), nullable=True),
    sa.Column('calories_total', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'date', name='uq_daily_activity_source_date')
    )
    op.create_index(op.f('ix_daily_activity_date'), 'daily_activity', ['date'], unique=False)
    op.create_table('manual_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('text_original', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_logs_logged_at'), 'manual_logs', ['logged_at'], unique=False)
    op.create_table('nutrition_days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('salt_g', sa.Float(), nullable=True),
    sa.Column('water_ml', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_payloads_received_at'), 'raw_payloads', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_payloads_source'), 'raw_payloads', ['source'], unique=False)
    op.create_table('recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('resources_pct', sa.Float(), nullable=True),
    sa.Column('stress', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'date', name='uq_recovery_source_date')
    )
    op.create_index(op.f('ix_recovery_date'), 'recovery', ['date'], unique=False)
    op.create_table('sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('deep_s', sa.Integer(), nullable=True),
    sa.Column('rem_s', sa.Integer(), nullable=True),
    sa.Column('light_s', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'date', name='uq_sleep_source_date')
    )
    op.create_index(op.f('ix_sleep_date'), 'sleep', ['date'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('training_effect_aerobic', sa.Float(), nullable=True),
    sa.Column('vo2max_est', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_workouts_source_external_id')
    )
    op.create_index(op.f('ix_workouts_started_at'), 'workouts', ['started_at'], unique=False)
    op.create_table('nutrition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('meal', sa.String(length=64), nullable=True),
    sa.Column('product', sa.String(length=256), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('salt_g', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['day'], ['nutrition_days.date'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_nutrition_items_source_external_id')
    )
    op.create_index(op.f('ix_nutrition_items_day'), 'nutrition_items', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_items_day'), table_name='nutrition_items')
    op.drop_table('nutrition_items')
    op.drop_index(op.f('ix_workouts_started_at'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_sleep_date'), table_name='sleep')
    op.drop_table('sleep')
    op.drop_index(op.f('ix_recovery_date'), table_name='recovery')
    op.drop_table('recovery')
    op.drop_index(op.f('ix_raw_payloads_source'), table_name='raw_payloads')
    op.drop_index(op.f('ix_raw_payloads_received_at'), table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_table('nutrition_days')
    op.drop_index(op.f('ix_manual_logs_logged_at'), table_name='manual_logs')
    op.drop_table('manual_logs')
    op.drop_index(op.f('ix_daily_activity_date'), table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_chat_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_body_composition_measured_at'), table_name='body_composition')
    op.drop_table('body_composition')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_memory_agent'), table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
