"""ingest_state

Revision ID: 4cb0a4737e01
Revises: ff70f1c88efa
Create Date: 2026-09-18 14:24:03.905261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb0a4737e01'
down_revision: Union[str, Sequence[str], None] = 'ff70f1c88efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_state',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('last_synced_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingest_state')
    # ### end Alembic commands ###
