"""agent_runs.tools_called

Revision ID: e0e4e7f51ec3
Revises: 10eaeff03c27
Create Date: 2026-09-17 19:59:35.427636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e4e7f51ec3'
down_revision: Union[str, Sequence[str], None] = '10eaeff03c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('tools_called', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'tools_called')
    # ### end Alembic commands ###
